### ISSUE TITLE
Can't install on Ubuntu 20.04 with Python 3.9

### ISSUE THREAD

**Issue by tkschuler** [Farama-Foundation/ViZDoom#519]
I cannot install on Ubuntu 20.04 with Python 3.9.  I've tried installing with the provided python setup and build files as well as building manually from source,  both fail at the very end.  I've used the script ./linux_check_dependencies and everything seems to be installed,  so I'm not really sure what to do from here?  

```
[100%] Built target libvizdoom_python
[100%] Linking CXX executable ../../../bin/vizdoom
/usr/bin/ld: CMakeFiles/vizdoom.dir/tempfiles.cpp.o: in function 'FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0xb): warning: the use of 'tempnam''is dangerous, better use 'mkstemp'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to 'uuid_parse@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to 'uuid_generate_random@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to 'uuid_unparse@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to 'uuid_copy@UUID_1.0'
collect2: error: ld returned 1 exit status
make[2]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:5543: bin/vizdoom] Error 1
make[1]: *** [CMakeFiles/Makefile2:713: src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Installation failed, you may be missing some dependencies. 
Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details

Traceback (most recent call last):
  File "/home/schuler/Documents/RLTutorials/games/doom/ViZDoom/setup.py", line 147, in <module>
    setup(
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/schuler/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/schuler/Documents/RLTutorials/games/doom/ViZDoom/setup.py", line 138, in run
    subprocess.check_call(['make', '-j', str(cpu_cores)])
  File "/home/schuler/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '15']' returned non-zero exit status 2.
```

**Comment by mwydmuch** [comment]
Hi @tkschuler, thank you for reporting the problem. I'm traveling this weekend, and I will investigate this at the beginning of the next week. I'm sorry I can't help you earlier.

**Comment by MetallicaSPA** [comment]
I'm having the same issue. Tried to build in Ubuntu 22.04 and 22.10 (updated from the 22.04) and can't do it. Any updates?

**Comment by mwydmuch** [comment]
Hi, @MetallicaSPA I couldn't replicate the problem. Are you also using Anaconda 3.9 with GCC 9?

**Comment by hbonnavaud** [comment]
Hi, I just installed conda 23.7.2, and created a virtual environment with python 3.7 and got the same problem when trying to install vizdoom. 
Also tested with python 3.9.
For both of them I followed the steps specified for conda environment in the readme file.
I tested it on ubuntu 20.04.
Any help ?

**Comment by mwydmuch** [comment]
Hi @hbonnavaud, sorry to hear that. I tried to replicate this problem using the docker container with Ubuntu 20.04 and the conda version specified by you (the latest) and, unfortunately, cannot replicate that problem, it builds ok for me. Could you copy-paste the output of the failed installation command?I will look more into that later. 

But I have good news. We are going to release binary wheels for all Python versions next week, and this will remove all compilation problems like this.

**Comment by hbonnavaud** [comment]
Basically, I have this error when I try to install vizdoom in a python 3.7 venv using pip install vizdoom
```
  -- Generating done (0.1s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      
      Installation failed, you may be missing some dependencies.
      Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Installation.md for details
      
      Traceback (most recent call last):
        File "/home/disc/h.bonnavaud/these/implems/sfl/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/disc/h.bonnavaud/these/implems/sfl/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/disc/h.bonnavaud/these/implems/sfl/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 252, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 417, in build_wheel
          wheel_directory, config_settings)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 242, in <module>
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2qrdig9c/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 186, in run
        File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_EXECUTABLE=/usr/bin/python3.7']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects
```

And This error when I try to install it in a python 3.7 conda environment, following the instruction specific to conda environment in the readme:

```
/usr/bin/ld: CMakeFiles/vizdoom.dir/tempfiles.cpp.o: in function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0xb): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to `uuid_parse@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to `uuid_generate_random@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to `uuid_unparse@UUID_1.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libfontconfig.so: undefined reference to `uuid_copy@UUID_1.0'
collect2: error: ld returned 1 exit status
make[2]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:5534: bin/vizdoom] Error 1
make[1]: *** [CMakeFiles/Makefile2:713: src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Installation failed, you may be missing some dependencies. 
Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Installation.md for details

Traceback (most recent call last):
  File "setup.py", line 241, in <module>
    "research",
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "setup.py", line 187, in run
    subprocess.check_call(["make", "-j", str(cpu_cores)])
  File "/home/disc/h.bonnavaud/anaconda3/envs/sfl/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '15']' returned non-zero exit status 2.
```

I will try using a docker container.

**Comment by hbonnavaud** [comment]
Don't know how you did @mwydmuch, I tried with docker and followed the steps in the readme, 

Here is the error installing vizdoom in docker container ubuntu:20.04 with python3.7

```
root@6cb313011049:/# pip install vizdoom
Collecting vizdoom
  Downloading vizdoom-1.2.0.tar.gz (15.7 MB)
     |████████████████████████████████| 15.7 MB 379 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting gymnasium>=0.28.0
  Downloading gymnasium-0.28.1-py3-none-any.whl (925 kB)
     |████████████████████████████████| 925 kB 27.5 MB/s 
Collecting pygame>=2.1.3
  Downloading pygame-2.5.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 9.3 MB/s 
Collecting numpy
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 5.4 MB/s 
Collecting farama-notifications>=0.0.1
  Downloading Farama_Notifications-0.0.4-py3-none-any.whl (2.5 kB)
Collecting typing-extensions>=4.3.0
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting importlib-metadata>=4.8.0; python_version < "3.10"
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting cloudpickle>=1.2.0
  Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting jax-jumpy>=1.0.0
  Downloading jax_jumpy-1.0.0-py3-none-any.whl (20 kB)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp1wol2c0l build_wheel /tmp/tmprqa9mq3s
       cwd: /tmp/pip-install-s5pfatnq/vizdoom
  Complete output (89 lines):
  running bdist_wheel
  running build
  CMake Warning:
    No source or binary directory provided.  Both will be assumed to be the
    same as the current working directory, but note that this warning will
    become a fatal error in future CMake releases.
  
  
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  CMake Error at /tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem thread system
    date_time chrono regex iostreams) (Required is at least version "1.65.0")
  Call Stack (most recent call first):
    /tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    /tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindBoost.cmake:2378 (find_package_handle_standard_args)
    CMakeLists.txt:101 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  
  Installation failed, you may be missing some dependencies.
  Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Installation.md for details
  
  Traceback (most recent call last):
    File "/tmp/tmp1wol2c0l", line 280, in <module>
      main()
    File "/tmp/tmp1wol2c0l", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp1wol2c0l", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 417, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 242, in <module>
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
      self.run_command("build")
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-70c0q892/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 186, in run
    File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_EXECUTABLE=/usr/bin/python3.7']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom which use PEP 517 and cannot be installed directly
```

I tried with the conda steps in a conda env with python 3.7, but I got the exact same error than without docker

**Comment by mwydmuch** [comment]
Thanks for the information and output @hbonnavaud. I'm using the variation of https://github.com/Farama-Foundation/ViZDoom/blob/master/tests/local_builds_dockerfiles/apt%2Bconda-based.Dockerfile for testing.

However, as I said, today we released the 1.2.1 version with Python binary wheels. So you no longer need to build it, and you can install it on Linux by simply running `pip install vizdoom` without any deps. I hope this helps!

**Comment by hbonnavaud** [comment]
Hi, sound wired to me that you managed to install it on ubuntu 20.04.
I just gave it a new try using docker image ubuntu:20.04, here is a video :
https://youtu.be/owTwu6blNKQ

(I'm not sure about the video quality so here is a resume)

```
docker pull ubuntu:20.04
docker run -it ubuntu:20.04 /bin/bash
```

In container

```
apt-get update
apt install cmake git libboost-all-dev libsdl2-dev libopenal-dev
apt-get install python3-pip
pip install --upgrade pip
pip install vizdoom
```

Am I missing something ?

**Comment by hbonnavaud** [comment]
Indeed, it work well now. Thank you for your help.

**Comment by hbonnavaud** [comment]
Hi (again ...) It's been a while, and this building error still occurs. I just created a venv on a computing cluster (debian) and python3 -m pip install vizdoom still call cmake and try to build vizdoom. It is disapointing. I cannot understand how such a library fail to pip install half of the time...

**Comment by mwydmuch** [comment]
Hi @hbonnavaud, I'm sorry to hear that you still have a problem with installing ViZDoom. Let me help you to solve the problem. Have you checked/updated your pip to the latest version (or at least above 0.21)? The old versions of pip are unable to install manylinux_X_Y wheels, and fallback to the installation from source, which requires to have dependencies installed.

**Comment by hbonnavaud** [comment]
![image](https://github.com/Farama-Foundation/ViZDoom/assets/45778095/04902be9-07e9-42d3-b5ef-7c56b91d4731)

**Comment by hbonnavaud** [comment]
Wait my bad, It just saw I'm using python 3.6, let me test with later versions

**Comment by hbonnavaud** [comment]
Yep 
![image](https://github.com/Farama-Foundation/ViZDoom/assets/45778095/3bd5458d-d66d-4f13-b8ac-32f3eb583413)

**Comment by hbonnavaud** [comment]
Not debian but redhat sorry 
![image](https://github.com/Farama-Foundation/ViZDoom/assets/45778095/a9e5e260-65a4-47c7-be5c-f2ac6ed9a83c)
ldd --version
![image](https://github.com/Farama-Foundation/ViZDoom/assets/45778095/2cb8297f-3d4d-4554-82d5-d773d1d248b9)

**Comment by mwydmuch** [comment]
Thank you for the information. Unfortunately, ViZDoom wheels are not compatible with RedHat 7 (which was released in 2014, and uses old glib 2.17 from 2012). ViZDoom requires glib >=2.28 (which is available in RedHat >=8 and most Linux distros released in 2018/2019). 

Because of that incompatibility, `pip install` tries to install (build) ViZDoom from the source. 
It requires the following dependencies on RedHat to be installed first. 
```
yum install cmake git boost-devel SDL2-devel openal-soft-devel
```
However, I cannot guarantee it will be successful because versions of these packages available on yum for RedHat 7 can also be too old for ViZDooom to compile successfully (CMake 3.12+, GCC 6.0+, Boost libraries 1.54.0+ are required).

So, if it's available on your cluster, I would recommend using docker to run images with a more modern Linux distro. 

Also, I'm sorry ViZDoom doesn't work out of the box on your system. I mainly maintain this library in my free time, and I don't have the capacity to ensure compatibility with old distros (which, at this point, would require me to basically downgrade some parts of the code base).

**Comment by mwydmuch** [comment]
I'm closing the issue again as the problem of @hbonnavaud was diagnosed and explained.
